environment: production

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://groundhog.la" # the base hostname & protocol for your site, e.g. http://example.com

jekyll_tidy:
  compress_html: false

plugins:
  - jekyll-tidy
  - jekyll-sitemap

sass:
  style: compressed
